### ISSUE TITLE
Windows build is scrubbing year and journal title data when exporting deduped file

### ISSUE THREAD

**Issue by JP1363** [CREBP/sra-dedupe-ui#3]
I've tried every combination of upload into the DeDupe-UI tool and download possible but whichever combination I use, the exported results always omit the year data field and the journal title data field.

**Comment by hash-bang** [comment]
Sorry about that. I'm at a conference right now but will fix this up when I get a chance.

**Comment by hash-bang** [comment]
New version of the sra-dedupe-ui should now fix this issue.

Was an outdated version of the upstream `reflib` dependency, but I ended up down a rabbit hole updating Electron, WebPack and other packages to actually recompile the thing.

Please reopen if you are still having issues.
